### ISSUE TITLE
Traffic Light states and speed limits

### ISSUE THREAD

**Issue by kargarisaac** [cjy1992/gym-carla#1]
Hi,

Thank you for sharing this great code. I'm playing with the code and have a question. Do you think it is possible to add traffic light states and speed limits to the birdeye view and render it as some channel or on the same image? Is it possible with Carla?

Thank you

**Comment by cjy1992** [comment]
Yes it is possible. We can get the traffic light and speed limit information in Carla. In https://arxiv.org/abs/1903.00640 I put the traffic light information to the birdview by changing the color of routing. However I later found the way I extract traffic light information is not very accurate. Thus the traffic light info is currently not shown in this repo, but it definitely can be added. For speed limit, the "no rendering mode" in the official Carla repo render it by adding a traffic sign besides the road. But I don't think this is a good way to add the speed limit information, a better way might be drawing the color of the lane in proportion to the speed limit as in the ChauffeurNet paper https://arxiv.org/pdf/1812.03079.pdf.

**Comment by kargarisaac** [comment]
Thank you for your replay. Yes, I found it and as you said, it's not accurate. Thank you for references.
