### ISSUE TITLE
Multiple instances for parallel training

### ISSUE THREAD

**Issue by kargarisaac** [cjy1992/gym-carla#4]
Hi,
I'm trying to use Carla with stable_baselines and SubprocVecEnv for vectorized env and parallel training but it gives me some error like:
`
RuntimeError: trying to access an expired episode; a new episode was started in the simulation but an object tried accessing the old one.
`
Is it possible to use Carla for parallel training? It's too slow for single env training.

Thank you

**Comment by cjy1992** [comment]
As far as I know, CARLA does not support this kind of parallel simulation. However, It can open multiple simulation servers, with each server assigned a different port number, and then use python client with the corresponding port number to connect to each server. Hope this helps.
On the other hand, it's actually not that necessary to parallelize the environment for speeding up training a reinforcement learning agent in CARLA. In our works, we find it takes about one to two days to converge (with RGB images inputs) if introducing a latent model, see https://arxiv.org/abs/2001.08726 and https://ieeexplore.ieee.org/abstract/document/8917306. I think this speed is acceptable, and we can see significant progress of average return soon in few hours after training starts. If you are interested, you can try our code https://github.com/cjy1992/interp-e2e-driving.
