### ISSUE TITLE
Create costmap

### ISSUE THREAD

**Issue by vehxianfish** [cjy1992/gym-carla#7]
Hi cjy,
     Thank you for your great code ~ which inspire me a lot.espically the visualization is so wonderful.
     Now I want to create a costmap as mentioned in the title to do motion plan experiments.I find the repo exist a costmap branch,but I can't undestand code clearly.Could you please give me some advice？

Best,

Filip

**Comment by cjy1992** [comment]
Hi Filip,

Thanks for your interest. For the cost map branch, it basically creates a costmap for feasible lanes, that the area within a feasible lane is assigned low cost, and otherwise a high cost.

**Comment by vehxianfish** [comment]
Thanks for your reply!
There is another problem:
In file render.py,
`hero_front = self.hero_transform.get_forward_vector()` 
can you give detailed explanation for func 'get_forward_vector()',eg return object.
thanks in advance!

**Comment by cjy1992** [comment]
Hi, this is a CARLA object, please refer to CARLA documentations.
